/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupproject2_imgs;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Frame;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prathibha
 */
public class ImageSelect extends javax.swing.JFrame {

    
    UnzipFiles un = new UnzipFiles();
    
    CreateZip cz= new CreateZip();
    
    File inputzip,outputdir = null;
    File[] files = null;
    File [] files2 = new File[50];
    
    int j=0;
    static Vector<String> columnNames1;
    static Vector<Vector> tablecreated;
    
    ArrayList<File> files3 =new ArrayList<File>();
    
    
    setTable st= new setTable();
    
    
    String SaveFilePath= null;
    String Dir = null;
    
    GetDetails getD= new GetDetails();
    String forDetails= null;
    
    
    int xmouse;
    int ymouse;
    
    
    public ImageSelect() {
        initComponents();
        reset();
        
       
    }
    
    public void reset(){
        jPanel1.setVisible(false);
        lblAgeC.setVisible(false);
        lblAgeCDisplay.setVisible(false);
        lblArea1.setVisible(false);
        lblAreaDisplay1.setVisible(false);
        lblImageSetDetails.setVisible(false);
        lblSex1.setVisible(false);
        lblSexDisplay1.setVisible(false);
        lblweightC1.setVisible(false);
        lblweightCDisplay.setVisible(false);
        lblNoofImages.setVisible(false);
        lblNoofImagesDisplay.setVisible(false);
        lblSelectedImgName.setVisible(false);
        lblImageNameDisplay.setVisible(false);
        btnDelete.setVisible(false);
        btnZip.setVisible(false);
        btnSetsaveZipPath.setVisible(false);
        btnchoise.setVisible(false);
        Slider1.setVisible(false);
        lblSelectedNotice.setVisible(false);
        lblSaveDirectory.setVisible(false);
        tfSaveFilePath.setVisible(false);
    
    
    }
    
    public void loadT(){
        columnNames1=new Vector<String>();
        columnNames1.addElement("<html><font face=\"Helvetica Neue\" size=\"4\" ><b>Selected IMG</font></html>");
        
        
        //tableSetupTime=se.getSectionWiseTime(files2);
        //jTable1.setModel(new DefaultTableModel(tableSetupTime, columnNames1));
        tablecreated=st.setTableSelect(files3);
        tblSelectedImg.setModel(new DefaultTableModel(tablecreated, columnNames1));
    }
    
    public void sortByNumber(File[] file) {
        Arrays.sort(file, new Comparator<File>() {
            @Override
            public int compare(File o1, File o2) {
                int n1 = extractNumber(o1.getName());
                int n2 = extractNumber(o2.getName());
                return n1 - n2;
            }

            private int extractNumber(String name) {
                int i = 0;
                try {
                    int s = name.indexOf('I')+1;
                    int e = name.lastIndexOf('.');
                    String number = name.substring(s, e);
                    i = Integer.parseInt(number);
                } catch(Exception e) {
                    i = 0; // if filename does not match the format
                           // then default to 0
                }
                return i;
            }
        });

        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelectedImgName = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblminimize = new javax.swing.JLabel();
        lblSelectedNotice = new javax.swing.JLabel();
        lblAgeCDisplay = new javax.swing.JLabel();
        lblAgeC = new javax.swing.JLabel();
        lblweightCDisplay = new javax.swing.JLabel();
        lblweightC1 = new javax.swing.JLabel();
        lblSex1 = new javax.swing.JLabel();
        lblArea1 = new javax.swing.JLabel();
        lblAreaDisplay1 = new javax.swing.JLabel();
        lblSexDisplay1 = new javax.swing.JLabel();
        lblImageSetDetails = new javax.swing.JLabel();
        lblSaveDirectory = new javax.swing.JLabel();
        lblNoofImagesDisplay = new javax.swing.JLabel();
        lblNoofImages = new javax.swing.JLabel();
        lblImageNameDisplay = new javax.swing.JLabel();
        tfSaveFilePath = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSelectedImg = new javax.swing.JTable();
        btnZip = new javax.swing.JButton();
        btnSelectImagesZip = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnchoise = new javax.swing.JButton();
        btnSetsaveZipPath = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitle = new javax.swing.JLabel();
        lblProgetTitle = new javax.swing.JLabel();
        Slider1 = new javax.swing.JSlider();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1100, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSelectedImgName.setFont(new java.awt.Font("Avenir", 0, 16)); // NOI18N
        lblSelectedImgName.setForeground(new java.awt.Color(204, 204, 204));
        lblSelectedImgName.setText("Selected Image :");
        getContentPane().add(lblSelectedImgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 120, -1));

        lblClose.setFont(new java.awt.Font("Avenir Next", 1, 18)); // NOI18N
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
        });
        getContentPane().add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1073, 7, 17, 20));

        lblminimize.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        lblminimize.setText("-");
        lblminimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblminimizeMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimizeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblminimizeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblminimizeMouseEntered(evt);
            }
        });
        getContentPane().add(lblminimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 7, 17, 20));

        lblSelectedNotice.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        lblSelectedNotice.setForeground(new java.awt.Color(204, 204, 204));
        lblSelectedNotice.setText("selected image details");
        getContentPane().add(lblSelectedNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 220, -1));

        lblAgeCDisplay.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAgeCDisplay.setForeground(new java.awt.Color(255, 255, 255));
        lblAgeCDisplay.setText("age");
        getContentPane().add(lblAgeCDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 282, 80, -1));

        lblAgeC.setFont(new java.awt.Font("Avenir", 0, 16)); // NOI18N
        lblAgeC.setForeground(new java.awt.Color(204, 204, 204));
        lblAgeC.setText("Age Category :");
        getContentPane().add(lblAgeC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        lblweightCDisplay.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblweightCDisplay.setForeground(new java.awt.Color(255, 255, 255));
        lblweightCDisplay.setText("weight");
        getContentPane().add(lblweightCDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 402, 60, -1));

        lblweightC1.setFont(new java.awt.Font("Avenir", 0, 16)); // NOI18N
        lblweightC1.setForeground(new java.awt.Color(204, 204, 204));
        lblweightC1.setText("Weight Category :");
        getContentPane().add(lblweightC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        lblSex1.setFont(new java.awt.Font("Avenir", 0, 16)); // NOI18N
        lblSex1.setForeground(new java.awt.Color(204, 204, 204));
        lblSex1.setText("Sex :");
        getContentPane().add(lblSex1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        lblArea1.setFont(new java.awt.Font("Avenir", 0, 16)); // NOI18N
        lblArea1.setForeground(new java.awt.Color(204, 204, 204));
        lblArea1.setText("Area :");
        getContentPane().add(lblArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        lblAreaDisplay1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAreaDisplay1.setForeground(new java.awt.Color(255, 255, 255));
        lblAreaDisplay1.setText("Area");
        getContentPane().add(lblAreaDisplay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 322, 160, -1));

        lblSexDisplay1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblSexDisplay1.setForeground(new java.awt.Color(255, 255, 255));
        lblSexDisplay1.setText("gender");
        getContentPane().add(lblSexDisplay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 362, 80, -1));

        lblImageSetDetails.setFont(new java.awt.Font("Avenir Next", 1, 18)); // NOI18N
        lblImageSetDetails.setText("<html><u>Image Set Details</u></html>");
        getContentPane().add(lblImageSetDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 200, -1));

        lblSaveDirectory.setFont(new java.awt.Font("Avenir", 0, 16)); // NOI18N
        lblSaveDirectory.setForeground(new java.awt.Color(204, 204, 204));
        lblSaveDirectory.setText("Save Directory :");
        getContentPane().add(lblSaveDirectory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        lblNoofImagesDisplay.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblNoofImagesDisplay.setForeground(new java.awt.Color(255, 255, 255));
        lblNoofImagesDisplay.setText("no");
        getContentPane().add(lblNoofImagesDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 442, 50, -1));

        lblNoofImages.setFont(new java.awt.Font("Avenir", 0, 16)); // NOI18N
        lblNoofImages.setForeground(new java.awt.Color(204, 204, 204));
        lblNoofImages.setText("No_Of_Images :");
        getContentPane().add(lblNoofImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        lblImageNameDisplay.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblImageNameDisplay.setForeground(new java.awt.Color(255, 255, 255));
        lblImageNameDisplay.setText("name");
        getContentPane().add(lblImageNameDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 482, 90, -1));

        tfSaveFilePath.setBackground(new java.awt.Color(204, 204, 204));
        tfSaveFilePath.setBorder(null);
        tfSaveFilePath.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        tfSaveFilePath.setSelectionColor(new java.awt.Color(0, 153, 255));
        getContentPane().add(tfSaveFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 250, 20));

        jPanel1.setLayout(new java.awt.CardLayout());

        jScrollPane1.setForeground(new java.awt.Color(0, 153, 153));

        tblSelectedImg.setBackground(new java.awt.Color(204, 204, 204));
        tblSelectedImg.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        tblSelectedImg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "<html><font face=\"Helvetica Neue\" size=\"4\" ><b>Selected IMG</font></html>"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSelectedImg.setGridColor(new java.awt.Color(204, 204, 204));
        tblSelectedImg.setSelectionBackground(new java.awt.Color(0, 153, 255));
        tblSelectedImg.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tblSelectedImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSelectedImgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSelectedImg);

        jPanel1.add(jScrollPane1, "card2");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 220, 480));

        btnZip.setFont(new java.awt.Font("Avenir", 0, 16)); // NOI18N
        btnZip.setText("Zip");
        btnZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZipActionPerformed(evt);
            }
        });
        getContentPane().add(btnZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 110, 30));

        btnSelectImagesZip.setFont(new java.awt.Font("Avenir Next", 0, 21)); // NOI18N
        btnSelectImagesZip.setText("SELECT IMAGES");
        btnSelectImagesZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectImagesZipActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectImagesZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 180, 200, 40));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(844, 630, 230, -1));

        btnchoise.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        btnchoise.setText("Select");
        btnchoise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchoiseActionPerformed(evt);
            }
        });
        getContentPane().add(btnchoise, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 178, 110, 30));

        btnSetsaveZipPath.setText("...");
        btnSetsaveZipPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetsaveZipPathActionPerformed(evt);
            }
        });
        getContentPane().add(btnSetsaveZipPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 538, 60, -1));

        lblImage.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblImage.setForeground(new java.awt.Color(204, 204, 204));
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setText("<html>\n<h1><font color = black>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\nINSTRACTIONS</h1><br>\n&nbsp;&nbsp;&nbsp;This tool is designed to select the images that are using to &nbsp;&nbsp;do the measurement part of this system.\nFirst you should &nbsp;&nbsp;&nbsp;&nbsp;click <b><font color = white>SELECT IMAGES</b> button and select the path to the &nbsp;images that are downloaded \nfrom the central repository. You &nbsp;&nbsp;don't need to extract the zip file that is downloaded from the &nbsp;&nbsp;&nbsp;&nbsp;central repo. \nYou just need to select the ZIP file form the &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;image selection.\nThen using <b><font color = white>Side-bar</b> you can see those &nbsp;&nbsp;images and using <b><font color = white>Select</b> button you can select those images &nbsp;&nbsp;to be done the measurment task. \nSelected images will show &nbsp;&nbsp;&nbsp;on the table. Delete images from table are allowed. \nFinally &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b><font color = white>ZIP</b> button will create the zip file that contains all the &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;selected images. \nYou can set the save path also.  \n</html>");
        getContentPane().add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 161, 510, 510));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 1090, 10));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("IMAGE SELECTION FOR FACIAL TISSUE THICKNESS MEASUREMENT");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 650, 40));

        lblProgetTitle.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        lblProgetTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblProgetTitle.setText("Neuroimaging Data Portal for DICOM Data Management");
        getContentPane().add(lblProgetTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        Slider1.setBackground(new java.awt.Color(102, 102, 102));
        Slider1.setMajorTickSpacing(100);
        Slider1.setMinimum(1);
        Slider1.setMinorTickSpacing(100);
        Slider1.setPaintTicks(true);
        Slider1.setToolTipText("");
        Slider1.setValue(1);
        Slider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Slider1StateChanged(evt);
            }
        });
        Slider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Slider1MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slider1MouseClicked(evt);
            }
        });
        getContentPane().add(Slider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 105, 540, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/groupproject2_imgs/images/IMGS2.3.png"))); // NOI18N
        lblBackground.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBackgroundMouseDragged(evt);
            }
        });
        lblBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBackgroundMousePressed(evt);
            }
        });
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblSelectedImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSelectedImgMouseClicked
        // TODO add your handling code here:
        
        lblSelectedNotice.setVisible(true);
        
        lblSelectedNotice.setVisible(true);
        int x = tblSelectedImg.getSelectedRow();
        ImageIcon i1 = new ImageIcon(files3.get(x).getAbsolutePath());
        lblImage.setIcon(i1);
        lblSelectedNotice.setText("Selected Image" + files3.get(x).getName());
        
    }//GEN-LAST:event_tblSelectedImgMouseClicked

    private void btnSelectImagesZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectImagesZipActionPerformed
        // TODO add your handling code here:
        //lblImage.setText("");
        JFileChooser chooser = new JFileChooser("/Users/prathibha/Desktop/D2Jpeg");
        chooser.setMultiSelectionEnabled(true);
        int returnvalue= chooser.showOpenDialog(null);
        if (returnvalue == JFileChooser.APPROVE_OPTION) {
            inputzip = chooser.getSelectedFile();
            
            
            forDetails= inputzip.getName();
            //System.out.println("getname "+forDetails);
            String x=inputzip.getAbsolutePath();
            x=x.replace(".zip", "");
            Dir = x;
            un.unzip(inputzip.getAbsolutePath(), x);
            
            File folder = new File(x);
            files = folder.listFiles();
            
            
            //Slider1.setMaximum(files.length - 2);
            int i = Slider1.getValue();
            //System.out.println("Slider- "+i);
            j = i;

            ImageIcon i1 = new ImageIcon(files[1].toString());
        
            lblImage.setIcon(i1);
            ImageIcon i2 = new ImageIcon(getClass().getResource("images/IMGS2.4.png"));
            //ImageIcon i2 = new ImageIcon("images/IMGS2.4.png");
            lblBackground.setIcon(i2);
            
            String[] dtl=getD.AllDeatis(forDetails);
            lblAgeCDisplay.setText(dtl[2]);
            lblAreaDisplay1.setText(dtl[3]);
            lblSexDisplay1.setText(dtl[4]);
            lblweightCDisplay.setText(dtl[5]);
            lblNoofImagesDisplay.setText(String.valueOf(files.length));
            lblImageNameDisplay.setText(x);
            
            
            lblAgeC.setVisible(true);
            lblAgeCDisplay.setVisible(true);
            lblArea1.setVisible(true);
            lblAreaDisplay1.setVisible(true);
            lblImageSetDetails.setVisible(true);
            lblSex1.setVisible(true);
            lblSexDisplay1.setVisible(true);
            lblweightC1.setVisible(true);
            lblweightCDisplay.setVisible(true);
            lblNoofImages.setVisible(true);
            lblNoofImagesDisplay.setVisible(true);
            lblSelectedImgName.setVisible(true);
            lblImageNameDisplay.setVisible(true);
            
            //btnDelete.setVisible(true);
            //btnZip.setVisible(true);
            //btnSetsaveZipPath.setVisible(true);
            btnchoise.setVisible(true);
            Slider1.setVisible(true);
            //lblSelectedNotice.setVisible(true);
            //lblSaveDirectory.setVisible(true);
            //tfSaveFilePath.setVisible(true);
            
            //folder.delete();
            //save all files on the directory
            /*for (int i = 0; i < files.length; i++) {
                if (files[i].isFile()) {
                    System.out.println("File " + files[i]);
                } else if (files[i].isDirectory()) {
                    System.out.println("Directory " + files[i]);
                }
            }
            */
            
            System.out.println("length-" + files.length);
            
            //System.out.println("path"+files[0].getAbsolutePath());
            sortByNumber(files);
            
            btnSelectImagesZip.setVisible(false);
        }
    }//GEN-LAST:event_btnSelectImagesZipActionPerformed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        // TODO add your handling code here:
        lblClose.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        lblClose.setForeground(Color.LIGHT_GRAY);
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        lblClose.setForeground(Color.black);
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.HAND_CURSOR);
        lblClose.setForeground(Color.white);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblminimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizeMousePressed
        // TODO add your handling code here:
        lblminimize.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblminimizeMousePressed

    private void lblminimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizeMouseClicked
        // TODO add your handling code here:
        lblminimize.setForeground(Color.LIGHT_GRAY);
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lblminimizeMouseClicked

    private void lblminimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizeMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        lblminimize.setForeground(Color.black);
    }//GEN-LAST:event_lblminimizeMouseExited

    private void lblminimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizeMouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.HAND_CURSOR);
        lblminimize.setForeground(Color.white);
    }//GEN-LAST:event_lblminimizeMouseEntered

    private void Slider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Slider1StateChanged
        // TODO add your handling code here:

        Slider1.setMaximum(files.length - 2);
        int i = Slider1.getValue();
        //System.out.println("Slider- "+i);
        j = i;

        ImageIcon i1 = new ImageIcon(files[i].toString());
        
        lblImage.setIcon(i1);
        lblImageNameDisplay.setText(""+files[i].getName());
        
        //value2.setText("" + jSlider1.getValue());
        float f = i;
        float j = (f / files.length) * 100;
        int x = Math.round(j);
        //System.out.println(x);
        //Slider1.setValue(x);
        /*else if(jSlider1.getValue()==100){
            ImageIcon i1= new ImageIcon(files[1].toString());
            value.setIcon(i1);
        }*/
    }//GEN-LAST:event_Slider1StateChanged

    private void Slider1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slider1MousePressed
        // TODO add your handling code here:
        lblSelectedNotice.setVisible(false);
    }//GEN-LAST:event_Slider1MousePressed

    private void Slider1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slider1MouseClicked
        // TODO add your handling code here:
        lblSelectedNotice.setVisible(false);
    }//GEN-LAST:event_Slider1MouseClicked

    private void btnchoiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchoiseActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        lblImageNameDisplay.setText(files[j].getName());
        //System.out.println("cout"+files2[j]);
        if (!(files3.contains(files[j]))) {
            files3.add(files[j]);

            System.out.println(files3.get(0));
            
            btnDelete.setVisible(true);
            btnZip.setVisible(true);
            btnSetsaveZipPath.setVisible(true);
            //btnchoise.setVisible(true);
            //Slider1.setVisible(true);
            //lblSelectedNotice.setVisible(true);
            lblSaveDirectory.setVisible(true);
            tfSaveFilePath.setVisible(true);
            
            
            
            loadT();
        } else {
            ConfirmationMessage cm = new ConfirmationMessage("Image already selected..!!!", "Warning");
            cm.setVisible(true);
        }
    }//GEN-LAST:event_btnchoiseActionPerformed

    private void btnZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZipActionPerformed
        // TODO add your handling code here:
        int fileZize=files3.size();
        String filesize2 = String.valueOf(fileZize);
        System.out.println("filesize----"+filesize2);
        String Zipname= getD.getZipnameH(forDetails, filesize2);
        //System.out.println("Zipname-"+Zipname);
        if(SaveFilePath!=null){
            
        
        try {
            // TODO add your handling code here:

            cz.ZipCreateExample(files3, SaveFilePath,Zipname);
        } catch (Exception ex) {
            Logger.getLogger(ImageSelect.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else{
            System.out.println("hariynne ne path eka set ne");
        }
        
        System.out.println("dir "+Dir);
        File folder = new File(Dir);
        folder.listFiles();
        System.out.println(folder.list());
        
        String[] entries = folder.list();
        for (String s : entries) {
            File currentFile = new File(folder.getPath(), s);
            currentFile.delete();
        }
        folder.delete();
        
    }//GEN-LAST:event_btnZipActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int x = tblSelectedImg.getSelectedRow();
        //System.out.println(files2[x].getName());
        files3.remove(x);
        //files2[x]= files2[x+2];
        loadT();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSetsaveZipPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetsaveZipPathActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser("/Users/prathibha/Desktop");
        chooser.setMultiSelectionEnabled(true);
        chooser.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY);
        int returnvalue= chooser.showOpenDialog(null);
        
        if (returnvalue == JFileChooser.APPROVE_OPTION) {
            //files3 = chooser.getSelectedFile();
            SaveFilePath = chooser.getSelectedFile().getAbsolutePath();
            System.out.println("save file path -"+SaveFilePath);
            tfSaveFilePath.setText(SaveFilePath);
            //tfSaveFilePath.disable();
            //ZipPath = files3.getAbsolutePath();
            
        }
    }//GEN-LAST:event_btnSetsaveZipPathActionPerformed

    private void lblBackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_lblBackgroundMousePressed

    private void lblBackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_lblBackgroundMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider Slider1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSelectImagesZip;
    private javax.swing.JButton btnSetsaveZipPath;
    private javax.swing.JButton btnZip;
    private javax.swing.JButton btnchoise;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAgeC;
    private javax.swing.JLabel lblAgeCDisplay;
    private javax.swing.JLabel lblArea1;
    private javax.swing.JLabel lblAreaDisplay1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImageNameDisplay;
    private javax.swing.JLabel lblImageSetDetails;
    private javax.swing.JLabel lblNoofImages;
    private javax.swing.JLabel lblNoofImagesDisplay;
    private javax.swing.JLabel lblProgetTitle;
    private javax.swing.JLabel lblSaveDirectory;
    private javax.swing.JLabel lblSelectedImgName;
    private javax.swing.JLabel lblSelectedNotice;
    private javax.swing.JLabel lblSex1;
    private javax.swing.JLabel lblSexDisplay1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblminimize;
    private javax.swing.JLabel lblweightC1;
    private javax.swing.JLabel lblweightCDisplay;
    private javax.swing.JTable tblSelectedImg;
    private javax.swing.JTextField tfSaveFilePath;
    // End of variables declaration//GEN-END:variables
}
